package gemini

import (
	"context"

	"github.com/praneeth-ayla/autocommenter/internal/ai/providerutil"
	"github.com/praneeth-ayla/autocommenter/internal/contextstore"
	"github.com/praneeth-ayla/autocommenter/internal/prompt"
	"github.com/praneeth-ayla/autocommenter/internal/scanner"
	"google.golang.org/genai"
)

func (g *GeminiProvider) GenerateReadme(contexts []contextstore.FileDetails, existingReadme string) (string, error) {
	ctx := context.Background()

	client, err := genai.NewClient(ctx, nil) // Initialize the Gemini client.
	if err != nil {
		return "", err
	}

	tree, err := providerutil.BuildFileTree(scanner.GetProjectRoot()) // Build a file tree representation of the project.
	if err != nil {
		return "", err
	}

	promptText, err := prompt.BuildReadmePrompt(contexts, existingReadme, tree) // Construct the prompt for README generation.
	if err != nil {
		return "", err
	}

	config := &genai.GenerateContentConfig{
		SystemInstruction: &genai.Content{
			Parts: []*genai.Part{
				{Text: prompt.SystemInstructionReadme}, // Set the system instruction for README generation.
			},
		},
		ResponseMIMEType: "text/plain", // Request plain text output.
	}

	input := []*genai.Content{
		{Parts: []*genai.Part{{Text: promptText}}}, // Provide the generated prompt as input.
	}

	result, err := client.Models.GenerateContent(
		ctx,
		"gemini-2.5-pro", // Specify the Gemini model to use.
		input,
		config,
	)
	if err != nil {
		return "", err
	}

	out := result.Text()
	// Add attribution footer
	out += "\n\n---\n*This README was automatically generated by [AutoCommenter](https://github.com/praneeth-ayla/autocommenter)*" // Append an attribution footer to the generated README.

	return out, nil
}
